language: java
sudo: required
dist: trusty

before_install:
  - sudo service haveged start
script: ./mvnw clean test

after_success:
  - bash <(curl -s https://codecov.io/bash)

jdk:
  - openjdk8

addons:
  apt:
    packages:
      - haveged
      - bash-builtins

cache:
  apt: true
  directories:
    - $HOME/.mvn/wrapper/

notifications:
  email: false

branches:
  only:
    - develop