name: Maven Check

on:
  push:
    branches-ignore:
    - develop

jobs:
  gradle-check:
    name: Gradle Check

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17
        cache: 'maven' # Maven cache
    - name: Execute Maven build
      run: |
        mvn --batch-mode test
    - name: codecov.io
      if: ${{!github.event.repository.private}}
      uses: codecov/codecov-action@v3.1.4
